services:
  backend:
    image: osmansuastegui/tournament-management-back  # Use the Docker Hub image for backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/basket
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: osman
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_DB: basket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: osman
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

