version: '3.8'

services:
  backend:
    image: osmansuastegui/tnt:backend  # Use the Docker Hub image for backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/basket
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: osmansuastegui/tnt:13-alpine  # Use the Docker Hub image for PostgreSQL
    container_name: db
    environment:
      POSTGRES_DB: basket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network

  frontend:
    image: osmansuastegui/tnt:frontend  # Use the Docker Hub image for frontend
    container_name: frontend
    ports:
      - "80:80"  # Map host port 80 to container port 80 (or adjust as needed)
    networks:
      - app-network

networks:
  app-network:
    name: app-network  # Explicitly set the network name here
    driver: bridge
