name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tournament-management-back -f Dockerfile .
    
    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_USERNAME}}/tournament-management-back

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up SSH to Connect to EC2
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Step 2: Upload Docker Compose File to EC2
    - name: Upload Docker Compose File
      run: |
        scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@${{ secrets.EC2_HOST }}:/path/to/docker-compose/directory/docker-compose.yml

    # Step 3: Deploy Services on EC2
    - name: Deploy Backend and Database
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /path/to/docker-compose/directory
          docker-compose pull
          docker-compose down
          docker-compose up -d
        EOF
