name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - './github/workflows/**'
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tournament-management-back -f Dockerfile .
    
    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_USERNAME}}/tournament-management-back
